[package]
name = "problem4"
version = "0.1.0"
authors = ["engineer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
bincode = "1.2.1"


[dependencies.xor]
path = "../xor"
